# Hw4-Written Hw Q3 and 4

In [1]:
# Import Important Libraries
import sklearn
from sklearn.datasets import load_breast_cancer # taking included data set from Sklearn http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html
from sklearn.linear_model import LogisticRegression # importing Sklearn's logistic regression's module
from sklearn import preprocessing # preprossing is what we do with the data before we run the learning algorithm
from sklearn.model_selection import train_test_split 
import numpy as np

import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

HW4, q3 

In [2]:
import numpy as np

def hypothesis(x , w):
    z = np.dot(x, w)
    return 1/(1 + np.exp(-z))

def likelihood(x, y, w):
    yhat = hypothesis(X, w)
    likelihood = np.sum(y * np.log(yhat) + (1 - y) * np.log(1 - yhat)) 
    return likelihood

X = np.array([[0.49,0.09,1.69,0.04,0.04, 0.64, 1, 0.16],[0.16,0.09,0.25,0,0.49,0,0.04,0.01]]).reshape(8,2)
x_one = np.ones((8,1)) # add one column
X = np.hstack((x_one, X))

w_1 = np.array([0.66,-2.24,-0.18]).reshape(3,1)
w_2 = np.array([1.33, -2.96, -2.77]).reshape(3,1)

y = np.array([0,0,0,0,1,1,1,1]).reshape(8,1)

print(f'Check X =\n {X}, the shape of X is {X.shape}')
print(f'Check y = {y.transpose()}, the shape of X is {y.shape}')
print(f'Check w = {w_1.transpose()}, the shape of w is {w_1.shape}')
print(f'Check w\' = {w_2.transpose()}, the shape of w\' is {w_2.shape}')

print(f'h_w(x) is:\n {hypothesis(X, w_1)}')
print(f'h_w\'(x) is:\n {hypothesis(X, w_2)}')

print(f'likelihood of w is {likelihood(X,y,w_1)}')
print(f'likelihood of w\' is {likelihood(X,y,w_2)}')


Check X =
 [[1.   0.49 0.09]
 [1.   1.69 0.04]
 [1.   0.04 0.64]
 [1.   1.   0.16]
 [1.   0.16 0.09]
 [1.   0.25 0.  ]
 [1.   0.49 0.  ]
 [1.   0.04 0.01]], the shape of X is (8, 3)
Check y = [[0 0 0 0 1 1 1 1]], the shape of X is (8, 1)
Check w = [[ 0.66 -2.24 -0.18]], the shape of w is (3, 1)
Check w' = [[ 1.33 -2.96 -2.77]], the shape of w' is (3, 1)
h_w(x) is:
 [[0.38845766]
 [0.04177438]
 [0.61187487]
 [0.16675528]
 [0.57086961]
 [0.52497919]
 [0.39231299]
 [0.63844007]]
h_w'(x) is:
 [[0.40861351]
 [0.02224374]
 [0.36326985]
 [0.11172906]
 [0.64727899]
 [0.64336515]
 [0.46993631]
 [0.76564831]]
likelihood of w is -4.25271239754217
likelihood of w' is -3.015879343821497


# Loading the data set.

In the below code cell, you will load the data from sklearn using the method given. Check import statements and use the given function

In [3]:
# TODO Q01
cancer = load_breast_cancer()

In [4]:
# VERIFY - Print the shape of data and target
print('Q01 - cancer.target.shape: ', cancer.target.shape)
print('Q01 - cancer.data.shape: ', cancer.data.shape)

Q01 - cancer.target.shape:  (569,)
Q01 - cancer.data.shape:  (569, 30)


# Data Pre-Processing
Scale before splitting the data into train and test since we will be using gradient ascent. 
* Use `preprocessing` to scale the data. 
* Assign the target of cancer to variable `y (<np.ndarray>)`.
* Use `train_test_split` to split the data (`75% train` and `25% test`) to `X_train`, `X_test`, `y_train`, `y_test` with `random_state` of 42
* Reshape `y_train` into 2D array `y_2d_train` and `y_test` into 2D array `y_2d_test`

In [5]:
# TODO Q02
X_scale = preprocessing.scale(cancer.data)
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(X_scale, y, random_state=42, train_size=0.75, test_size=0.25)
# print(X_train)
# print(X_test)
# print(y_train)
# print(y_test)
y_2d_train = y_train.reshape((y_train.shape[0], 1))
y_2d_test = y_test.reshape((y_test.shape[0], 1))
# print(y_2d_train)
# print(y_2d_test)


# Implementing Logistic Regression Using Gradient Ascent

In [6]:
# TODO Q03
# Write the sigmoid function
def sigmoid(z):
    result = 1 / (1 + np.exp(-z))
    return result

In [7]:
# TODO Q04
# Append a column of ones to X_train
# ones is a  vector of shape n,1
ones = np.ones((X_train.shape[0], 1))
# print(ones)
# Append a column of ones in the beginning of X_train an save in variable X_train_1(<np.ndarray>).
X_train_1 = np.hstack((ones, X_train))

In [8]:
# TODO Q05
# Initialize Parameter Vector w to a zero matrix with shape (X_train_1.shape[1],1)
w_init = np.zeros(((X_train_1.shape[1],1)))

In [9]:
# VERIFY
print('Q05 - w_init.shape: ', w_init.shape)

Q05 - w_init.shape:  (31, 1)


In [10]:
# TODO Q06
# Write the hypothesis function
# this returns a vector of all sigmoids of all examples
# in other words, returns the probability between 0 and 1 of being class 1 of each example 
def hypothesis(X_train_1, w):
    z_score = X_train_1.dot(w)
    y_hat = sigmoid(z_score)
    return y_hat

In [11]:
# TODO Q07 
# Compute y_hat(<np.ndarray>) using X_train_1 and w_init
y_hat_init = hypothesis(X_train_1, w_init)

# Likelihood Function.
Write the code to calculate the log likelihood as discussed in the class.

In [12]:
# TODO Q08
# Write the log likelihood function
def likelihood(X_tr, y_tr, w, n):
    y_hat = hypothesis(X_tr, w) # is a vector of all probability of each example, basically h(x^(i)) for all i = 0 .. n
    likelihood = np.sum(y_tr * np.log(y_hat) + (1 - y_tr) * np.log(1 - y_hat))
    return likelihood

In [13]:
# VERIFY - The value should be equal to -295.2806989185367 using X_train_1, y_2d_train, w, X_train_1.shape[0].
print('Q08 - likelihood: ', likelihood(X_train_1, y_2d_train, w_init, X_train_1.shape[0]))

Q08 - likelihood:  -295.2806989185367


# Gradient Ascent with Ridge Regression

In [14]:
# TODO Q09
# Write the gradient ascent function
def Gradient_Ascent(X_train_1, y_2d_train, learning_rate, num_iters, alpha):
    # Number of training examples.
    N = X_train_1.shape[0]
    # Initialize w(<np.ndarray>). Zeros vector of shape X_train.shape[1],1
    w = np.zeros((X_train_1.shape[1], 1))
    # Initiating list to store values of likelihood(<list>) after few iterations.
    likelihood_values = []
    for i in range(num_iters):
        y_hat = hypothesis(X_train_1, w) 
        error = y_2d_train - y_hat 
        gradient = X_train_1.T.dot(error) 
        # Updating Parameters
        ridgeDeriv = 2 * w 
        w = w + (learning_rate / N) * gradient - alpha *  ridgeDeriv
        if (i % 100) == 0:
            likelihood_values.append(likelihood(X_train_1,y_2d_train,w,N))
        
    return w, likelihood_values

In [15]:
learning_rate = 0.75
num_iters = 10000
alpha = 0.0001 #lambda in this case
w_gradient_ascent, likelihood_values = Gradient_Ascent(X_train_1, y_2d_train, learning_rate, num_iters, alpha)
print(w_gradient_ascent)


[[-0.3371506 ]
 [-0.07965755]
 [-0.16694649]
 [ 0.11512502]
 [-0.31074216]
 [-0.37634795]
 [ 2.60738557]
 [-1.27817525]
 [-3.02236987]
 [ 0.88708933]
 [-0.84121432]
 [-3.24493654]
 [ 0.65548693]
 [-0.17323638]
 [-2.11810957]
 [-0.31472541]
 [ 0.24429312]
 [ 0.18858105]
 [-1.26221572]
 [ 1.30240782]
 [ 1.92300053]
 [-1.56868421]
 [-2.44457231]
 [-0.06114289]
 [-1.70997665]
 [-0.15616728]
 [ 0.64091936]
 [-2.23502552]
 [-0.80024716]
 [-2.56680736]
 [-0.4002247 ]]


In [16]:
def predict(X_train_1, w):
    y_hat = sigmoid(X_train_1.dot(w))
    return y_hat

In [17]:
from sklearn.model_selection import KFold

def kfold_cross_validation(X_train_1, y):
    lambdas = [1,0.00001,0.001, 0.1, 10, 0.01, 0.0001, 0.00000001]
    #print("All possible lambdas:", lambdas)
    best_lambda = 0
    kfold_model = KFold(n_splits=5, random_state=None, shuffle=False)
    min_error = float('inf')
    w_best = []
    for l in lambdas:
        #print(l)
        error = []
        wval = []
        for train_index, test_index in kfold_model.split(X_train_1):
            X_tr = X_train_1[train_index]
            Y_tr = y[train_index].reshape((-1, 1))
            X_ts = X_train_1[test_index]
            Y_ts = y[test_index].reshape((-1, 1))
            w, likelihood = Gradient_Ascent(X_tr, Y_tr, 0.001, X_tr.shape[0], l)
            yhat = hypothesis(X_ts, w)
            error.append(np.sum((y-yhat)**2))
            wval.append(w)

        if (np.mean(error) < min_error):
            min_error = np.mean(error)
            w_best = wval[np.argmin(error)]
            best_lambda = l

        #print("Min error",min_error)
            
    return w_best, best_lambda

In [18]:
w_best, best_lambda = kfold_cross_validation(X_train_1, y)
print("Best lambda:", best_lambda)

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in exp
  after removing the cwd from sys.path.
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in multiply
  """
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:16: RuntimeWarning: overflow encountered in multiply
  app.launch_new_instance()
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in multiply
Best lambda: 1e-08


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=76220f38-ae8c-4d04-96a1-7ad7bcfb080e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>